score-spec/score-go

loader/loader_test.go
types/resources.go

Adds support for resource annotations (see [#56](https://github.com/score-spec/spec/issues/56)) and resource inputs hints (see [#9](https://github.com/score-spec/spec/issues/9)).

Add support for resource annotations and inputs hints

---

loader/loader_test.go
schema/schema.go
schema/schema_test.go
schema/validate_test.go
types/resources.go

Updated Score schema and go library with deprecated resource properties definitions.

Deprecated resource properties definitions

---

loader/loader_test.go
schema/schema.go
schema/schema_test.go
types/containers.go

Added missing `host` and `scheme` properties into `httpGet` probe spec

fix: added missing host and scheme properties into httpGet probe spec

---

README.md
go.mod
loader/loader.go
loader/loader_test.go

This fixues up the go module path for v1. It turns out go modules only support the /vX suffix for version 2 and higher. 
So for now we've tagged an explicit v0 tag and we'll keep the same module path as before but with tags > v1.

fixed: go module path for v1

---

.gitignore
Makefile
README.md
loader/loader_test.go
schema/validate_test.go
types/types.gen.go
types/types.go

The generated types for `metadata` and `resource.*.metadata` were broken because the code generator ignored the `additionalProperties` and instead generated concrete types without any support for additional metadata entries.
Unfortunately we need the best of both worlds: an arbitrary map, while still checking for required properties during validation.
To fix this we generate the types from a 'modified' version of the spec in which we treat it like a generic map[string]interface{}. This 'modified' version is generated from a Makefile which also allows us to better codify the update-schema process.
The validation continues to use the raw spec file which can validate the required fields within the arbitrary object.
This library will then be imported into score-compose and any other score …

fix: fixed generated types for workload and resource metadata

---

loader/loader_test.go
schema/files/Makefile
schema/files/samples/score-full.yaml
schema/files/score-v1b1.json
schema/schema_test.go
schema/validate.go
schema/validate_test.go
types/types.gen.go

Score specification updates:
```
515c899 fix: make httpGet probe port required, fix volume read_only to be camelCase (#13)
2fb2c34 feat: added field restrictions and tests to the repository (#12)
```
This carries the following "breaking" changes:
1. Removed multiline file content string
2. Renamed volume read_only field to readOnly
To mitigate any impact on customers in the short term, there is a new function `ApplyCommonUpgradeTransforms` which can automatically apply these transforms to a spec before validation and transformation. This can then be used to train or adapt customers to use the new types, and this functionality can be disabled or skipped on a customer-by-customer basis if required.
Any other restrictions are formalizations of existing documented limitations or are otherwise …

chore: updated score schema and types, added compatibility transformer

---

loader/loader_test.go
schema/files/score-v1b1.json
types/types.gen.go

Latest score schema improves the requirements on the http probe headers. This is low priority but worth updating to in score-go too for any implementations that can pick this up soon.
No breaking changes to customers unless they have deliberately misconfigured http headers on a liveness probe.

Updated score schema for http probe headers and updated tests to match

---

schema/files/README.md
schema/files/samples/score-full.yaml
schema/files/score-v1b1.json

64fee38 feat: added specification of workload.metadata.annotations (#17)
git-subtree-dir: schema/files
git-subtree-split: 64fee38c5326c54afc76d089aab8470e0bfce303

chore: updated 'schema/files/' changes from 136e984..64fee38

---

.github/workflows/ci.yml
CONTRIBUTING.md
NOTICE
loader/loader.go
loader/loader_test.go
loader/normalize.go
loader/normalize_test.go
schema/schema.go
schema/schema_test.go
schema/validate.go
schema/validate_test.go
types/types.go

Similar to the same change in score-compose: https://github.com/score-spec/score-compose/pull/81. This corrects the source code licensing headers and ensures the notice file exists.

chore: correct licensing headers of existing files

---

README.md
framework/override_utils.go
framework/override_utils_test.go
framework/resource_uid.go
framework/resource_uid_test.go
framework/state.go
framework/state_test.go
framework/substitution.go
framework/substitution_test.go
go.mod
go.sum
loader/loader.go
loader/loader_test.go
schema/validate.go
schema/validate_test.go

I'd like to make it easier to build alternative implementations of Score using the score-go library. So I've copied over some bits of score-compose (https://github.com/score-spec/score-compose/tree/main/internal/project, and https://github.com/score-spec/score-compose/blob/main/internal/command/override_utils.go) into score-go.
The major common parts are:
1. Applying map or path based overrides to the decoded yaml, here these have been re-implemented to not modify the input data structure.
2. Reading one or more score structures into an in-memory state object along with implementation-specific extras
3. Resolving a topologically-sorted list of resources and evaluating placeholders within them
These are mechanisms used in score-compose that are common to other implementations like …

feat: provide methods shared with score-compose for score implementation

---

framework/resource_uid.go
framework/state.go
framework/substitution.go
framework/substitution_test.go

There was some behavior inherited from an older version of score-compose that resolved 2 part placeholders like `${resources.<name>}` to `<name>`. This was used as a mechanism to refer to certain resources in some contexts (like volumes). A similar mechanism exists in some parts of Humanitec's implementation.
This funcitonality was ported over to score-go, but can now be removed and any special behavior can be moved into the implementations respectively. 
As an aside this PR also fixes some comments in other places that were incorrect.
This is what the score-compose PR would look like: https://github.com/score-spec/score-compose/pull/103

fix: remove deprecated 0-keys placeholder behavior

---

framework/state.go
framework/state_test.go

While upgrading a Score implementation at Humanitec I found a bug when processing a spec like the following (which was used in an existing unit test):
```
...
resources:
thing-a:
type: cat
id: garfield
params:
color: orange
thing-b:
type: cat
id: garfield
params:
color: orange 
```
This is an esoteric example which makes more sense when looking at multiple score workloads that define the same resource in the same project. The current main branch check was failing because deep-equal returned false because the metadata dictionaries were technically not the same outer type at the time of comparison.
The fix is just coercing it to the comparable type `map[string]interface{}`.
Specs like this (params or metadata defined only once) will still work fine without errors.
```
thing-a:
type: cat
id: …
```

fix(framework): fixed param/meta comparison for duplicate resource def with the same id

---

framework/state.go
framework/state_test.go

Resource provisioners have a common need to track the lifecycle of individual resources or assign them a real random uuid. This requires external state tracking but since it's a common need by score implementations we can add it here in the Score library.

feat: added guid (uuids) to resource state

---

framework/state.go
framework/state_test.go

A common problem found in the score implementations is that when loading the annotations from the metadata we find that nested maps like annotations have been coerced into the parent map type.

fix(framework): assert loaded workload and resource metadata annotations are coerced

---

framework/state.go
framework/state_test.go
types/types.go

This is a follow on from #39, but moves the support into the yaml decoding layer to reduce impact to other score implementations.

fix(types): universal improvement to metadata decoding

---

schema/files/score-v1b1.json

I've noticed that the containers section had an incorrect description. This PR should fix it. This shouldn't need to picked up in score-go, since the descriptions aren't used as such there.

fix: field description in the containers section

---

framework/substitution.go
framework/substitution_test.go

This adds supporting functionality for [score-compose#](https://github.com/score-spec/score-compose/issues/148) by allowing the unescape functionality to be customized. This convers the substituter into a struct which will support any further parameterized substitution in the future.

chore(placeholders): refactor matching capture and add regression test

---

uriget/example_test.go
uriget/uriget.go

I'd like to add a flag to the `score-compose` and `score-k8s` `init` subcommands for loading external provisioner files. This should mean that the user no longer needs to access the `.score-xyz` state directory themselves since this can be considered internal behavior.
We want to be able to pull in provisioners from the local filesystem, git, or http, so this `uriget` package supports this and provides an interface for reading files in this way. The git support calls the git binary on the system. This avoids needing a built in heavyweight client library and means we can take advantage of any auth sockets or global config.
Examples:
```
score-compose init \
--provisioners https://raw.githubusercontent.com/user/repo/public-provisioner/provisioners.yaml \
--provisioners …
```

feat: added common uriget package for fetching provisioners

---

uriget/example_test.go
uriget/uriget.go

It's an attempt to solve the issue faced by getOci
this PR added a new logic as said to retrieve the file and return it

fixed OCI image import bug

---

.github/workflows/ci.yml

Token-Permissions OpenSSF Scorecard check
> Reason: detected GitHub workflow tokens with excessive permissions
```
Warn: no topLevel permission defined: .github/workflows/ci.yml:1: Visit https://app.stepsecurity.io/secureworkflow/score-spec/score-go/ci.yml/main?enable=permissions
Tick the 'Restrict permissions for GITHUB_TOKEN'
Untick other options
```

Update ci.yml - explicit contents read permission

---

go.mod

- In `go.mod`: `1.23` --> `1.23.4`
For reproducible build/release based on a specific Go version.
Note: we could have the digest for the base image in the `Dockerfile`, but not going that path for now.

Update go.mod - 1.23.4

---

framework/state.go
framework/state_test.go
loader/normalize.go
types/types.go
types/types_test.go

This addresses two recent issues seen in new score implementations
1. Score implementations using score-go are blindly breaking non-utf-8 file characters when normalizing the score spec.
2. Score implementations often need to convert cpu and memory values to their native value ranges and suffixes so need a common file for parsing these values. I've been implementing a new Score implementation and need to convert between unit suffixes in a sane way.
3. Iteration order in PrimeResource was unstable leading to flakey tests and unexpected source workloads.

feat: added ParseResourceLimits utility and fixed mounted file encoding bug

---

uriget/example_test.go

Update example_test.go - fix 10-service.provisioners.yaml, integrating new version https://github.com/score-spec/community-provisioners/releases/tag/v0.4.0

Update example_test.go - fix 10-service.provisioners.yaml

---

CONTRIBUTING.md
formatter/output.go
formatter/output_test.go
go.mod
go.sum

Import output formatter library from score-compose implementation to avoid duplication of code between score-xxx cli implementation
Relates to score-spec/score-k8s#112

feat: add formatter output library
